env: dev

catalog: dev_catalog

schema_bronze: bronze
schema_silver: silver
schema_gold: gold

raw_data_path: /mnt/c/Users/Thinkpad/Downloads/data/retail_db/
checkpoint_path: /mnt/dev/checkpoints/orders

job:
  name: sales_pipeline_dev

cluster:
  spark_version: 13.3.x-scala2.12
  node_type_id: r5.xlarge
  num_workers: 1
