env: qa

catalog: qa_catalog

schema_bronze: bronze
schema_silver: silver
schema_gold: gold

raw_data_path: s3://amzn-s3-de-projects/raw
checkpoint_path: /mnt/dev/checkpoints/sales

cluster_workers: 3
