name: Deploy to Databricks

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: databricks

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_JOB_ID: ${{ secrets.DATABRICKS_JOB_ID }}
      # run: |
      #   databricks version
      #   echo "Updating job id: $DATABRICKS_JOB_ID"
      #   databricks jobs reset $DATABRICKS_JOB_ID --json-file workflows/job.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI (official)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      # - name: Configure Databricks Jobs API version
      #   run: |
      #     databricks jobs configure --version=2.1

      - name: Show Databricks CLI version
        run: |
          databricks version
     
      - name: Clean Databricks workspace folder
        run: |
          databricks workspace rm /Shared/databricks-sales-pipeline --recursive || true

      - name: Upload repo to Databricks Workspace
        run: |
          databricks workspace import-dir . /Shared/databricks-sales-pipeline

      - name: Verify job exists
        run: |
          databricks jobs get $DATABRICKS_JOB_ID
      
      - name: Update Databricks Job
        run: |
          databricks jobs reset $DATABRICKS_JOB_ID --json-file workflows/job.json
